[profile.default]
solc_version = "0.8.28"
evm_version = "cancun"
src = "src"
out = "out"
libs = ["lib"]
via_ir = true

[profile.cancun]
solc_version = "0.8.28"
evm_version = "cancun"
src = "src"
out = "out"
libs = ["lib"]
via_ir = true

[profile.shanghai]
solc_version = "0.8.28"
evm_version = "shanghai"
src = "src"
out = "out"
libs = ["lib"]
via_ir = true

[profile.london]
solc_version = "0.8.28"
evm_version = "london"
src = "src"
out = "out"
libs = ["lib"]
via_ir = false

fs_permissions = [{ access = "read", path = "./" }]

etherscan_api_key = "${ETHERSCAN_API_KEY}"

[rpc_endpoints]
# Mainnets
ethereum = "https://ethereum-rpc.publicnode.com"
optimism = "https://quaint-frequent-grass.optimism.quiknode.pro/c5bc8d8cf82b0388642982d6e7a0cfa561c49b0b/"
cronos = "https://evm.cronos.org"
bnb = "https://fabled-black-sanctuary.bsc.quiknode.pro/8dba6ccc07667feafd0dd6064281c2a46ae353ed/"
gnosis = "https://rpc.gnosis.gateway.fm"
unichain = "https://unichain-rpc.publicnode.com"
polygon = "https://solitary-bitter-layer.matic.quiknode.pro/a57a0dbd9436e681cfe0f6806dc835eec0e4c0b5/"
sonic = "https://rpc.soniclabs.com"
manta = "https://pacific-rpc.manta.network/http"
mint = "https://rpc.mintchain.io"
boba = "https://mainnet.boba.network"
zksync = "https://convincing-prettiest-frost.zksync-mainnet.quiknode.pro/a14018fec401cbe6626d8a200375555d21a5503e/"
shape = "https://mainnet.shape.network"
appchain = "https://appchain.calderachain.xyz/http"
worldchain = "https://worldchain-mainnet.g.alchemy.com/public"
redstone = "https://rpc.redstonechain.com/"
flow = "https://mainnet.evm.nodes.onflow.org"
hyperevm = "https://rpc.hyperliquid.xyz/evm"
metis = "https://andromeda.metis.io/?owner=1088"
polygon_zkevm = "https://zkevm-rpc.com"
lisk = "https://rpc.api.lisk.com"
sei = "https://evm-rpc.sei-apis.com"
perennial = "https://rpc.perennial.foundation"
story = "https://mainnet.storyrpc.io"
gravity = "https://rpc.gravity.xyz"
soneium = "https://rpc.soneium.org/"
swellchain = "https://swell-mainnet.alt.technology"
sanko = "https://mainnet.sanko.xyz"
ronin = "https://api.roninchain.com/rpc"
game7 = "https://mainnet-rpc.game7.io/"
abstract = "https://api.mainnet.abs.xyz"
morph = "https://rpc.morphl2.io"
hychain = "https://rpc.hychain.com/http"
mantle = "https://rpc.mantle.xyz"
ham = "https://rpc.ham.fun"
superseed = "https://mainnet.superseed.xyz"
cyber = "https://rpc.cyber.co"
powerloom = "https://rpc-v2.powerloom.network"
arena_z = "https://rpc.arena-z.gg"
b3 = "https://mainnet-rpc.b3.fun/http"
base = "https://aged-compatible-pine.base-mainnet.quiknode.pro/86247a56f7f36a0f0c0b10eb65061748f66bce7c/"
onchain_points = "https://rpc.onchainpoints.xyz"
apechain = "https://apechain.calderachain.xyz/http"
funki = "https://rpc-mainnet.funkichain.com"
mode = "https://mainnet.mode.network/"
arbitrum = "https://bold-few-mountain.arbitrum-mainnet.quiknode.pro/141c1fd7dd64a97d4d3c52d1487dbbefc55603b3/"
arbitrum_nova = "https://distinguished-boldest-layer.nova-mainnet.quiknode.pro/991046398297653a9f0ff1293ce912630986fd5f/"
celo = "https://forno.celo.org"
hemi = "https://rpc.hemi.network/rpc"
avalanche = "https://rough-late-energy.avalanche-mainnet.quiknode.pro/db7a0c340d1807fce83ffbf167b7ef909ab4089b/ext/bc/C/rpc/"
gunz = "https://rpc.gunzchain.io/ext/bc/2M47TxWHGnhNtq6pM5zPXdATBtuqubxn5EPFgFmEawCQr9WFML/rpc"
zircuit = "https://mainnet.zircuit.com"
superposition = "https://rpc.superposition.so"
ink = "https://rpc-qnd.inkonchain.com"
linea = "https://rpc.linea.build"
bob = "https://rpc.gobob.xyz/"
anime = "https://public-rpc.anime.xyz"
apex = "https://rpc.apex.proofofplay.com/8zMb1iBjJ37VwJkqYjMBg3AvtTbzWEs5q"
boss = "https://rpc.boss.proofofplay.com"
berachain = "https://rpc.berachain.com"
blast = "https://rpc.blast.io"
plume = "https://rpc.plume.org"
taiko = "https://rpc.taiko.xyz"
scroll = "https://rpc.scroll.io"
zero = "https://zero.drpc.org"
xai = "https://xai-chain.net/rpc"
katana = "https://rpc.katanarpc.com/FkJa1BMrbHboCvbfrCZJH9U5CHWpr3skv"
forma = "https://rpc.forma.art"
zora = "https://rpc.zora.energy/FkJa1BMrbHboCvbfrCZJH9U5CHWpr3skv"
corn = "https://mainnet.corn-rpc.com"
lordchain = "https://lordchain-rpc.appchain.base.org"
degen = "https://rpc.degen.tips/FkJa1BMrbHboCvbfrCZJH9U5CHWpr3skv"
ancient8 = "https://rpc.ancient8.gg/FkJa1BMrbHboCvbfrCZJH9U5CHWpr3skv"
rari = "https://mainnet.rpc.rarichain.org/http"
# Testnets
amoy = "https://polygon-amoy-bor-rpc.publicnode.com"
holesky = "https://ethereum-holesky.publicnode.com"
arbitrum_sepolia = "https://rpc.therpc.io/arbitrum-sepolia"
debank_testnet = "http://rpc.testnet.debank.com"
manta_testnet = "https://manta-pacific-testnet.drpc.org"
barret = "https://rpc-pop-testnet-barret-oxaolmcfss.t.conduit.xyz"
zksync_sepolia = "https://sepolia.era.zksync.dev"
align_testnet_v2 = "https://align-testnet.rpc.caldera.xyz/http"
mode_testnet = "https://sepolia.mode.network/8R2AbRhkvTrKgGyEWkmbSBGzjKbzKx1cv"
gin_testnet = "https://gin-testnet.alt.technology"
frame_testnet = "https://rpc.testnet.frame.xyz/infra-integration-http"
blast_sepolia = "https://fittest-lively-energy.blast-sepolia.quiknode.pro/e862635fdf062b6e592ea79d6af601edb77fe2a2/"
hypr = "https://rpc-testnet.hypr.network/"
hekla = "https://rpc.hekla.taiko.xyz"
op_sepolia = "https://rpc.therpc.io/optimism-sepolia"
ancient8_celestia_testnet = "https://rpcv2-testnet.ancient8.gg/8R2AbRhkvTrKgGyEWkmbSBGzjKbzKx1cv"
zora_sepolia = "https://sepolia.rpc.zora.energy"
funki_testnet = "https://funki-testnet.alt.technology"
lisk_sepolia = "https://rpc.sepolia-api.lisk.com"
cloud = "https://rpc-pop-testnet-cloud-fmg1z6e0a9.t.conduit.xyz"
game7_testnet = "https://rpc-game7-testnet-0ilneybprf.t.conduit.xyz"
shape_sepolia = "https://sepolia.shape.network/"
arbitrum_blueberry = "https://rpc.arb-blueberry.gelato.digital"
m_integrations_testnet = "https://rpc-m-integrations-testnet-kn5qqp4tzd.t.conduit-stg.xyz"
sepolia = "https://ethereum-sepolia-rpc.publicnode.com"
memecoin_2 = "https://rpc-memecoin-2-7m5e84e2pz.t.conduit.xyz"
base_sepolia = "https://sepolia.base.org"
bob_testnet = "https://testnet.rpc.gobob.xyz/"
b3_sepolia = "https://sepolia.b3.fun/http"
creator = "https://rpc-creator-335av30doc.t.conduit.xyz"
pop_cloud_testnet = "https://rpc-pop-testnet-cloud-fmg1z6e0a9.t.conduit.xyz"
secret = "https://rpc-secret-xj64ve9mdm.t.conduit.xyz"
mobl3_testnet = "https://sepolia.mobl3.xyz"
alleged_jade_loon = "https://rpc-alleged-jade-loon-fqlx1rs2zw.t.conduit.xyz"
kekchain = "https://rpc-kekchain-lvvulci8ai.t.conduit.xyz"
zero_testnet = "https://rpc.zerion.io/v1/zero-sepolia"
