[profile.default]
solc_version = "0.8.28"
evm_version = "cancun"
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
bytecode_hash = "none"
cbor_metadata = false

[profile.london]
solc_version = "0.8.28"
evm_version = "london"
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
bytecode_hash = "none"
cbor_metadata = false

[lint]
exclude_lints = ["mixed-case-function", "mixed-case-variable", "asm-keccak256"]

fs_permissions = [{ access = "read", path = "./" }]

etherscan_api_key = "${ETHERSCAN_API_KEY}"

[rpc_endpoints]
# Mainnets
ethereum = "${RPC_URL_ETHEREUM}"
optimism = "${RPC_URL_OPTIMISM}"
cronos = "${RPC_URL_CRONOS}"
bnb = "${RPC_URL_BNB}"
gnosis = "${RPC_URL_GNOSIS}"
unichain = "${RPC_URL_UNICHAIN}"
polygon = "${RPC_URL_POLYGON}"
sonic = "${RPC_URL_SONIC}"
manta = "${RPC_URL_MANTA}"
mint = "${RPC_URL_MINT}"
boba = "${RPC_URL_BOBA}"
zksync = "${RPC_URL_ZKSYNC}"
shape = "${RPC_URL_SHAPE}"
appchain = "${RPC_URL_APPCHAIN}"
worldchain = "${RPC_URL_WORLDCHAIN}"
redstone = "${RPC_URL_REDSTONE}"
flow = "${RPC_URL_FLOW}"
hyperevm = "${RPC_URL_HYPEREVM}"
metis = "${RPC_URL_METIS}"
polygon_zkevm = "${RPC_URL_POLYGON_ZKEVM}"
lisk = "${RPC_URL_LISK}"
sei = "${RPC_URL_SEI}"
perennial = "${RPC_URL_PERENNIAL}"
story = "${RPC_URL_STORY}"
gravity = "${RPC_URL_GRAVITY}"
soneium = "${RPC_URL_SONEIUM}"
swellchain = "${RPC_URL_SWELLCHAIN}"
sanko = "${RPC_URL_SANKO}"
ronin = "${RPC_URL_RONIN}"
game7 = "${RPC_URL_GAME7}"
abstract = "${RPC_URL_ABSTRACT}"
morph = "${RPC_URL_MORPH}"
hychain = "${RPC_URL_HYCHAIN}"
mantle = "${RPC_URL_MANTLE}"
somnia = "${RPC_URL_SOMNIA}"
ham = "${RPC_URL_HAM}"
superseed = "${RPC_URL_SUPERSEED}"
cyber = "${RPC_URL_CYBER}"
powerloom = "${RPC_URL_POWERLOOM}"
arena_z = "${RPC_URL_ARENA_Z}"
b3 = "${RPC_URL_B3}"
base = "${RPC_URL_BASE}"
plasma = "${RPC_URL_PLASMA}"
onchain_points = "${RPC_URL_ONCHAIN_POINTS}"
apechain = "${RPC_URL_APECHAIN}"
funki = "${RPC_URL_FUNKI}"
mode = "${RPC_URL_MODE}"
arbitrum = "${RPC_URL_ARBITRUM}"
arbitrum_nova = "${RPC_URL_ARBITRUM_NOVA}"
celo = "${RPC_URL_CELO}"
hemi = "${RPC_URL_HEMI}"
avalanche = "${RPC_URL_AVALANCHE}"
gunz = "${RPC_URL_GUNZ}"
zircuit = "${RPC_URL_ZIRCUIT}"
superposition = "${RPC_URL_SUPERPOSITION}"
ink = "${RPC_URL_INK}"
linea = "${RPC_URL_LINEA}"
bob = "${RPC_URL_BOB}"
anime = "${RPC_URL_ANIME}"
apex = "${RPC_URL_APEX}"
boss = "${RPC_URL_BOSS}"
berachain = "${RPC_URL_BERACHAIN}"
blast = "${RPC_URL_BLAST}"
plume = "${RPC_URL_PLUME}"
taiko = "${RPC_URL_TAIKO}"
syndicate = "${RPC_URL_SYNDICATE}"
scroll = "${RPC_URL_SCROLL}"
zero = "${RPC_URL_ZERO}"
xai = "${RPC_URL_XAI}"
katana = "${RPC_URL_KATANA}"
forma = "${RPC_URL_FORMA}"
zora = "${RPC_URL_ZORA}"
corn = "${RPC_URL_CORN}"
lordchain = "${RPC_URL_LORDCHAIN}"
degen = "${RPC_URL_DEGEN}"
metacade = "${RPC_URL_METACADE}"
ancient8 = "${RPC_URL_ANCIENT8}"
rari = "${RPC_URL_RARI}"
