[profile.default]
solc_version = "0.8.25"
src = "src"
out = "out"
libs = ["lib"]
via_ir = true

fs_permissions = [{ access = "read", path = "./"}]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
